LTP:fixed fallocate01 testcase
lsds/ltp pull request #37
Opened 2020-07-31 18:06 UTC by vamsikrishna935

* Patch Description: 
 * Test Failure reason in SGX-LKL: 
 * [[  SGX-LKL ]] libc_start_main_stage2(): Calling app main: /ltp/testcases/kernel/syscalls/fallocate/fallocate01
 * fallocate01    1  TCONF  :  fallocate01.c:233: fallocate system call is not implemented
 * Test is happening on temporary file created under /tmp, on which fallocate system call is failing.
 
 * Workaround to fix the issue:
 * fallocate system call is failing on temporary file created under /tmp directory.
 * So modified the tests to create directory in root filesystem.

2020-07-31 20:37 UTC, hukoyu requested changes
@vamsikrishna935 provided some feedback. Please address them. thanks

2020-07-31 20:37 UTC, hukoyu commented on testcases/kernel/syscalls/fallocate/fallocate01.c
> + */
Change to:

* Patch Description: 
  Test Failure reason in SGX-LKL: 
  [[  SGX-LKL ]] libc_start_main_stage2(): Calling app main: /ltp/testcases/kernel/syscalls/fallocate/fallocate01
  fallocate01    1  TCONF  :  fallocate01.c:233: fallocate system call is not implemented
  Test is happening on temporary file created under /tmp, on which fallocate system call is failing.
 
 * Workaround to fix the issue:
  fallocate system call is failing on temporary file created under /tmp directory.
  So modified the tests to create directory in root filesystem.

2020-07-31 20:37 UTC, hukoyu commented on testcases/kernel/syscalls/fallocate/fallocate01.c
> +       rmdir(tempdir);
indentation problem. before "git add", if you do "git diff" for a changed file, you can ctach the indentation issues.

2020-07-31 20:37 UTC, hukoyu commented on testcases/kernel/syscalls/fallocate/fallocate01.c
> +char *fname_mode1 = "tempdir/tfile_mode1";	/* Files used for testing */
Commend with // is bette then /* */ for one line. 
Also you can add same comment for the second file as well

2020-07-31 20:37 UTC, hukoyu commented on testcases/kernel/syscalls/fallocate/fallocate01.c
> +	// fallocate system call is failing temporary directory created using tst_tmpdir function.
Change to
// fallocate system call is failing to create temporary directory under /tmp using tst_tmpdir function.
// so,  creating test directory in root filesystem as workaroud
mkdir(tempdir, 0777);

2020-08-01 11:03 UTC, vamsikrishna935 commented
@hukoyu Yesterday i have pushed 2 commits excluding first commit, but my changes were not inline. Also in the commits it shows 2 instead of 3. Do you have any idea ?

2020-08-03 06:09 UTC, hukoyu commented
> @hukoyu Yesterday i have pushed 2 commits excluding first commit, but my changes were not inline. Also in the commits it shows 2 instead of 3. Do you have any idea ?

@vamsikrishna935  no idea. I see only two commits. Did you push your commit? 
Indentation and all my comments are nor addressed yet. It should be very easy to address my feedback. just 10 minutes.

2020-08-03 06:53 UTC, vamsikrishna935 commented
> 
> 
> > @hukoyu Yesterday i have pushed 2 commits excluding first commit, but my changes were not inline. Also in the commits it shows 2 instead of 3. Do you have any idea ?
> 
> @vamsikrishna935 no idea. I see only two commits. Did you push your commit?
> Indentation and all my comments are nor addressed yet. It should be very easy to address my feedback. just 10 minutes.

I have addressed and pushed, but in pr it is not reflecting. Only for this pr. I am working on it.

2020-08-03 17:03 UTC, vamsikrishna935 commented
Could not able push changes to this branch. Hence raised a new pr and closing this branch
https://github.com/lsds/ltp/pull/45/files

2020-08-03 17:03 UTC, closed without merging