Ken/issue297ltp
lsds/ltp pull request #51
Opened 2020-08-05 20:13 UTC by KenGordon

Various changes which add back in tests which provoke issue 297 (in the sgx-lkl repo https://github.com/lsds/sgx-lkl/issues/297). Many of the changes could be found by grepping but in the end I had to check a whole set of commits to lsds/ltp on the 28th of July "LTP patch*" which committed all the work on the testcases,  which had been kept as patches, one file at a time. Unfortunately I can't tell which files contained edits for this particular bug and also some files contained edits for more than one bug.

I accidently reintroduced code to test issue 405. I have left that in as 405 is recorded as closed and it didn't cause any failures when running the tests.

2020-08-06 03:05 UTC, hukoyu requested changes
@KenGordon overall it looks good. Thanks for reverting workarounds after issue lsds/sgx-lkl#297 is fixed.
I assume you looked at isue https://github.com/lsds/ltp/issues/13 for the tests updated with this workaround. 
I just saw in couple places you enabled tests comented with issue lsds/sgx-lkl#189, did you enable them by mistake? 
Also you uncommented one test but it doesn't mention issue 297 (or 169) can you double check. 
After you adress my three comments and if LTP tests pass after these changes it is all good for me.
Please share the link for sgx-lkl pipeline here so that we can verify tests are passing. Thanks

2020-08-06 03:05 UTC, hukoyu commented on testcases/kernel/syscalls/chown/chown04.c
> -       //{TEST_FILE5, EROFS} TODO: Enable after github issue 189 is fixed
This says enable after issue 189 fixed. With this PR issue 297 (and 169) fixed. Did you enable this by mistake?

2020-08-06 03:05 UTC, hukoyu commented on testcases/kernel/syscalls/chown/chown04.c
>         //SAFE_MOUNT(cleanup, device, "mntpoint", fs_type, MS_RDONLY, NULL); Should be replaced with below line after issue 189 fixed
This again says issue 189. Did you enable by mistake?

2020-08-06 03:05 UTC, hukoyu commented on testcases/kernel/syscalls/umount/umount02.c
> -//	{"Invalid address", NULL, EFAULT}, This test is commented because in SGX accessing NULL results in enclave exit
Is this issue 297 (or 169)?

2020-08-06 09:49 UTC, KenGordon commented on testcases/kernel/syscalls/chown/chown04.c
> -       //{TEST_FILE5, EROFS} TODO: Enable after github issue 189 is fixed
Yes. Good catch. Will sort it out. By the way I am on holiday for Thursday so it will be Friday,

2020-08-06 09:50 UTC, KenGordon commented on testcases/kernel/syscalls/chown/chown04.c
>         //SAFE_MOUNT(cleanup, device, "mntpoint", fs_type, MS_RDONLY, NULL); Should be replaced with below line after issue 189 fixed
Indeed.

2020-08-06 11:59 UTC, SeanTAllen commented
Can you open a PR for sgx-lkl that uses these changes. There's a lot here. Something could have been missed in review. It would be good to get CI runs going for this.

2020-08-06 15:57 UTC, hukoyu commented on testcases/kernel/syscalls/umount/umount02.c
> -//	{"Invalid address", NULL, EFAULT}, This test is commented because in SGX accessing NULL results in enclave exit
@KenGordon this is the only outstanding question for me. If you answer that then I can approve this PR. Thanks

2020-08-06 20:44 UTC, hukoyu commented
> Can you open a PR for sgx-lkl that uses these changes. There's a lot here. Something could have been missed in review. It would be good to get CI runs going for this.

@SeanTAllen  is this the corresponding sgx-lkl PR : https://github.com/lsds/sgx-lkl/pull/727
@KenGordon  ?

2020-08-06 20:45 UTC, SeanTAllen commented
It is.

2020-08-06 20:57 UTC, KenGordon commented
Yes.

> On 6 Aug 2020, at 21:44, hukoyu <notifications@github.com> wrote:
> 
> Can you open a PR for sgx-lkl that uses these changes. There's a lot here. Something could have been missed in review. It would be good to get CI runs going for this.
> 
> @SeanTAllen is this the corresponding sgx-lkl PR : lsds/sgx-lkl#727
> @KenGordon ?
> 
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub, or unsubscribe.
> 
> [ { "@context": "http://schema.org", "@type": "EmailMessage", "potentialAction": { "@type": "ViewAction", "target": "https://github.com/lsds/ltp/pull/51#issuecomment-670182803", "url": "https://github.com/lsds/ltp/pull/51#issuecomment-670182803", "name": "View Pull Request" }, "description": "View this Pull Request on GitHub", "publisher": { "@type": "Organization", "name": "GitHub", "url": "https://github.com" } } ]

2020-08-07 09:36 UTC, KenGordon commented on testcases/kernel/syscalls/umount/umount02.c
> -//	{"Invalid address", NULL, EFAULT}, This test is commented because in SGX accessing NULL results in enclave exit
It passed with the test enabled. after my fix.
I have checked using blame, but to no avail the patches having obscured stuff.
However if I remove my fix to setup.c and run with the test enabled it fails( ie fatal exit). Reapply the test and it passes (ie expected test behavior, running to completion).
So I am quite confident that the line needed to be commented out as a result of the bug in question, and now that the bug is fixed I need to reenable the test.
BTW I had not seen issue 13 prior to you mentioning it. TBH I don't fancy going through those files one at a time atgain from a different list.

// with fix and test enabled
umount02.c:60: PASS: umount() fails as expected: Invalid address. PASSED: EFAULT (14)   

// without fix and test enabled.
[[  SGX-LKL ]] FAIL: lkl_access_check failed: 0

2020-08-07 16:36 UTC, hukoyu approved these changes
Thanks for addressing feedback. LGTM.

2020-08-11 08:47 UTC, merged