LTP:Fixed rename14 testcase
lsds/ltp pull request #54
Opened 2020-08-06 18:28 UTC by rsrinivas01

Moved the test to use single process instead of multi process to verify the rename( ) syscall functionality.

2020-08-06 18:32 UTC, rsrinivas01 reviewed
@hukoyu , @shaikshavali1

Please review the changes for rename14 test case

2020-08-06 19:02 UTC, hukoyu requested changes
@rsrinivas01 please fix the indentation issue. @shaikshavali1 can you do a peer review first please.

2020-08-06 19:02 UTC, hukoyu commented on testcases/kernel/syscalls/rename/rename14.c
> +        if (ret == 0)
Fix the indentation problems

2020-08-07 15:30 UTC, shaikshavali1 requested changes
@rsrinivas01, Could you please modify the test case using threads.

2020-08-10 08:57 UTC, davidchisnall requested changes
This test appears to be complete nonsense.  It runs a loop where one process creates, unlinks, and closes a file (at which point the kernel should delete it).  Another process races to rename the file.  It appears that it is trying to fuzz the kernel for races involving renaming an unlinked file while it is concurrently closed.  If this test ever does fail, it's going to be incredibly hard to reproduce.  I think we're better off disabling this one.

2020-08-11 16:00 UTC, hukoyu commented
We will keep this test disabled as @davidchisnall  recommended. Closing the PR.

2020-08-11 16:00 UTC, closed without merging