LTP: Fixed unshare01 and unshare02
lsds/ltp pull request #64
Opened 2020-08-09 16:37 UTC by vamsikrishna935

* Patch Description:
	Test were failing because of no fork support.
	Modified the tests without using fork and done code cleanup.

2020-08-09 18:01 UTC, hukoyu approved these changes
LGTM

2020-08-10 09:05 UTC, davidchisnall requested changes
I don't understand this patch.  Unshare's behaviour is intrinsically linked to multiple processes, so we should just disable this test.

2020-08-11 03:37 UTC, vamsikrishna935 commented
> I don't understand this patch. Unshare's behaviour is intrinsically linked to multiple processes, so we should just disable this test.

@davidchisnall can we implement this using threads ?
Manpage statement : unshare() allows a process (or thread) to disassociate parts of its
       execution context that are currently being shared with other
       processes (or threads).

2020-08-11 08:08 UTC, davidchisnall commented
I’m not sure what man page you’re reading, but the one I have does not mention threads. That said, the design doc for unshare indicates it applies to threads created with clone. I have no idea whether this will work correctly until Vikas’ patch lands, but it looks as if it should be possible to enable this with threads.

2020-08-12 10:57 UTC, davidchisnall approved these changes
I think these changes are okay, the test itself is pretty useless: it tests that the syscall returns success, not that it actually does anything.

2020-08-12 17:12 UTC, merged